### ISSUE TITLE
Seems disingenuous to say 'trusted by millions'

### ISSUE THREAD

**Issue by popey456963** [online-notepad/infra-docs#1]
It appears that the Github repository is empty and the website is used rarely.

**Comment by lephuhai** [comment]
I'm develop ZNotepad.com within 24 hours and try keep it simple. Are you interest for ZNotepad @popey456963 ?

**Comment by popey456963** [comment]
That's very cool for you to develop this in 24 hours, quickly developing things is great!

But lying about your usage stats is less great.

**Comment by lephuhai** [comment]
Are you want to contribute to ZNotepad project and make it more great. Now, I don't have experience to viral and any marketing plan.

**Comment by popey456963** [comment]
I personally don't want to contribute to ZNotepad, I host an equivalent service.

Even without any experience in viral and marketing myself, I know that lying is not a good way to go about it.

**Comment by lephuhai** [comment]
Thank you for your attention, I will edit slogan to correctly and be more careful with the statements.

**Comment by lephuhai** [comment]
Changed: "Free online note trusted by millions" to **Simple Online Notepad**

**Comment by popey456963** [comment]
Thank you! ❤️
